theme: jekyll-theme-slate

title: Tribune collective des linguistes
description: Outre ses défauts fonctionnels, l’écriture inclusive pose des problèmes à ceux qui ont des difficultés d’apprentissage et, en réalité, à tous les francophones soudain privés de règles et livrés à un arbitraire moral." Bien que favorables à la féminisation de la langue, plusieurs linguistes estiment l'écriture inclusive profondément problématique.
