theme: jekyll-theme-slate

github:
  is_project_page: false

title: Tribune 
description: Outre ses défauts fonctionnels, l’écriture inclusive pose des problèmes à ceux qui ont des difficultés d’apprentissage.
