theme: jekyll-theme-slate

title: Tribune collective des linguistes
description: Outre ses défauts fonctionnels, l’écriture inclusive pose des problèmes à ceux qui ont des difficultés d’apprentissage.
